[package]
name = "rust-phi"
version = "0.1.0"
authors = ["KOBAYASHI Ittoku <nono381d815@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.20"
strum_macros = "0.20"
nalgebra = "0.26"
